//#define PIN_LED_RED 6
//#define PIN_LED_YELLOW 5
//#define PIN_LED_GREEN 4
//#define PIN_PUSHBUTTON 2

#define REG_DDR_LED_RED DDRH
#define REG_PORT_LED_RED PORTH
#define REG_PIN_LED_RED PINH
#define BIT_LED_RED 3

#define REG_DDR_LED_YELLOW DDRE
#define REG_PORT_LED_YELLOW PORTE
#define REG_PIN_LED_YELLOW PINE
#define BIT_LED_YELLOW 3

#define REG_DDR_LED_GREEN DDRG
#define REG_PORT_LED_GREEN PORTG
#define REG_PIN_LED_GREEN PING
#define BIT_LED_GREEN 5

#define REG_DDR_PUSHBUTTON DDRE
#define REG_PORT_PUSHBUTTON PORTE
#define REG_PIN_PUSHBUTTON PINE
#define BIT_PUSHBUTTON 4


void setup(){
  //pinMode(PIN_LED_RED, OUTPUT);
  //pinMode(PIN_LED_YELLOW, OUTPUT);
  //pinMode(PIN_LED_GREEN, OUTPUT);
  //pinMode(PIN_PUSHBUTTON, INPUT_PULLUP);
  REG_DDR_LED_RED |= _BV(BIT_LED_RED);
  REG_DDR_LED_YELLOW |= _BV(BIT_LED_YELLOW);
  REG_DDR_LED_GREEN |= _BV(BIT_LED_GREEN);
  //PORTD = 0x70;
  REG_DDR_PUSHBUTTON &= ~_BV(BIT_PUSHBUTTON);
  REG_PORT_PUSHBUTTON |= _BV(BIT_PUSHBUTTON); //turn on the internal pullup resister
  
}

void loop() {
  //if(!((REG_PIN_PUSHBUTTON >> BIT_PUSHBUTTON) & 0x01)) {
  if(bit_is_clear(REG_PIN_PUSHBUTTON, BIT_PUSHBUTTON)) {
    REG_PORT_LED_RED &= ~_BV(BIT_LED_RED);
    REG_PORT_LED_YELLOW &= ~_BV(BIT_LED_YELLOW);
  	REG_PORT_LED_GREEN |= _BV(BIT_LED_GREEN);
    delay(1000);
    REG_PORT_LED_RED &= ~_BV(BIT_LED_RED);
    REG_PORT_LED_YELLOW |= _BV(BIT_LED_YELLOW);
  	REG_PORT_LED_GREEN &= ~_BV(BIT_LED_GREEN);
	delay(500);
  }
    REG_PORT_LED_RED |= _BV(BIT_LED_RED);
    REG_PORT_LED_YELLOW &= ~_BV(BIT_LED_YELLOW);
  	REG_PORT_LED_GREEN &= ~_BV(BIT_LED_GREEN);
  
}